#CXXFLAGS += -I$(DIR_INSTALL)/opencv/include/opencv4

#LDFLAGS += -L$(DIR_INSTALL)/opencv/lib
#LDFLAGS += -L$(DIR_INSTALL)/opencv/lib/opencv4/3rdparty
#LDFLAGS += -L$(DIR_INSTALL)/zlib/lib
#
#LIBS += -lopencv_calib3d
#LIBS += -lopencv_core
#LIBS += -lopencv_dnn
#LIBS += -lopencv_features2d
#LIBS += -lopencv_flann
#LIBS += -lopencv_gapi
#LIBS += -lopencv_highgui
#LIBS += -lopencv_imgcodecs
#LIBS += -lopencv_imgproc
#LIBS += -lopencv_ml
#LIBS += -lopencv_objdetect
#LIBS += -lopencv_photo
#LIBS += -lopencv_stitching
#LIBS += -lopencv_video
#LIBS += -lopencv_videoio
#
#LIBS += -lade
#LIBS += -lIlmImf
#LIBS += -littnotify
#LIBS += -llibjpeg-turbo
#LIBS += -llibopenjp2
#LIBS += -llibpng
#LIBS += -llibprotobuf
#LIBS += -llibtiff
#LIBS += -llibwebp
#LIBS += -lquirc
#
#LIBS += -l:libz.a

include ../env.mk
